import { describe, expect, it } from 'vitest'
import contract from '../../shared/agent-runtime-contract.json'
import { DISCLOSURE_RECIPIENTS, TASK_EVENT_TYPES, type AgentInspectionView } from '../../shared/agent-contracts'
import { parseRuntimeConfig } from '../agent/packaged-runtime'
import { describeInspection } from '../../renderer/src/agent-task-view'
import { isAllowedRuntimeRoute, validateRuntimeSettings } from './agent-runtime-supervisor'
import { WireError, parseEventPage, parseInspection, parseInspectionAction, parseTask, projectRuntimeError } from './agent-wire'

type Json = Record<string, unknown>
const examples = contract.examples as unknown as Record<string, Json>
const schemas = contract.schemas as unknown as Record<string, { properties: Record<string, unknown>; required?: string[] }>
const TASK = '00000000-0000-4000-8000-000000000001'
const ACTION = '00000000-0000-4000-8000-000000000002'
const NOW = Date.parse('2026-09-16T10:01:00Z')

describe('page inspection contract (generated by the runtime)', () => {
  it('reads only declared, required fields', () => {
    const read: Record<string, string[]> = {
      InspectionResponse: ['action', 'observation', 'answer'],
      InspectionProposal: ['url', 'host', 'question', 'policy_version', 'disclosure'],
      RecordPageAnswerBody: ['observation_id', 'content_hash', 'answer', 'provider', 'model'],
      PrepareInspectionBody: ['disclosure']
    }
    for (const [model, fields] of Object.entries(read)) {
      for (const field of fields) expect(schemas[model].properties, `${model}.${field}`).toHaveProperty(field)
      for (const field of fields) expect(schemas[model].required ?? [], `${model}.${field}`).toContain(field)
    }
    // Literal-default fields are declared, and always present in stored proposals.
    for (const field of ['schema_version', 'operation', 'effect', 'limits']) {
      expect(schemas.InspectionProposal.properties).toHaveProperty(field)
      expect((examples.action_inspection_waiting.proposal as Json)[field]).toBeDefined()
    }
    // Prepare accepts a disclosure and nothing else: no URL, no question, no approval.
    expect(Object.keys(schemas.PrepareInspectionBody.properties)).toEqual(['disclosure'])
    expect(contract.errorCodes).toEqual(expect.arrayContaining([
      'destination_not_allowed', 'stale_observation', 'answer_not_grounded', 'observation_not_available', 'public_inspection_not_configured'
    ]))
    expect(TASK_EVENT_TYPES).toContain('task.page_answer_recorded')
    const recipients = (((schemas.RecordPageAnswerBody.properties.provider as Json).enum) as string[])
    expect(recipients).toEqual([...DISCLOSURE_RECIPIENTS])
  })

  it('parses the inspection task, card, answered, unknown and failed examples', () => {
    expect(parseTask(examples.task_inspection)).toMatchObject({
      kind: 'page_inspection',
      inspection: { url: 'https://github.com/satish9177/Lumi', host: 'github.com', question: 'What is this repository for?' }
    })
    const card = parseInspectionAction(examples.action_inspection_waiting)
    expect(card).toMatchObject({
      status: 'WAITING_APPROVAL', riskTier: 'R1',
      proposal: { url: 'https://github.com/satish9177/Lumi', host: 'github.com', recipients: ['gemini', 'openai'], maxTextChars: 12_000, maxLinks: 20 },
      approval: { status: 'PENDING', actionRevision: 2 }
    })

    const answered = parseInspection(examples.inspection_answered)
    expect(answered.view.answer).toMatchObject({ status: 'answered', provider: 'gemini', evidence: [{ block: 'b2' }] })
    expect(answered.view.observation).toMatchObject({ blockCount: 3, linkCount: 1, documentEpoch: 1, settled: true })
    // Page text for the model stays in main; the view has none of it.
    expect(answered.observation?.blocks).toHaveLength(3)
    expect(JSON.stringify(answered.view)).not.toContain('IGNORE PREVIOUS INSTRUCTIONS')

    const unknown = parseInspection(examples.inspection_outcome_unknown)
    expect(unknown.view).toMatchObject({ status: 'OUTCOME_UNKNOWN', attempts: [{ outcome: 'OUTCOME_UNKNOWN', errorCode: 'runtime_restart' }] })
    expect(unknown.observation).toBeUndefined()

    const failed = parseInspection(examples.inspection_failed_redirect)
    expect(failed.view.attempts[0]).toMatchObject({ outcome: 'FAILED', errorCode: 'redirect_blocked', refusal: 'destination_not_allowed' })

    const events = parseEventPage(examples.events_inspection, TASK, 0)
    expect(events.at(-1)).toMatchObject({ type: 'task.page_answer_recorded', answerStatus: 'answered' })
    expect(JSON.stringify(events)).not.toContain('desktop companion')
  })

  it('refuses a card that carries anything unreviewed', () => {
    const base = structuredClone(examples.action_inspection_waiting)
    for (const mutate of [
      (value: Json) => { (value.proposal as Json).selector = '#rating' },
      (value: Json) => { (value.proposal as Json).url = 'https://evil.example/' },
      (value: Json) => { (value.proposal as Json).operation = 'click' },
      (value: Json) => { ((value.proposal as Json).disclosure as Json).recipients = ['everyone'] },
      (value: Json) => { value.tool_name = 'commit_booking' }
    ]) {
      const value = structuredClone(base)
      mutate(value)
      expect(() => parseInspectionAction(value)).toThrow(WireError)
    }
    const tampered = structuredClone(examples.inspection_answered)
    ;((tampered.observation as Json).blocks as Json[])[0].id = 'b9'
    expect(() => parseInspection(tampered)).toThrow(WireError)
  })

  it('explains a refused destination with the runtime reason', () => {
    expect(projectRuntimeError(422, examples.error_destination)).toEqual({
      code: 'destination_not_allowed', message: 'That website is not on Lumi’s list of sites it may inspect.'
    })
  })

  it('main may reach exactly the three inspection routes', () => {
    expect(isAllowedRuntimeRoute('POST', `/tasks/${TASK}/inspection/prepare`)).toBe(true)
    expect(isAllowedRuntimeRoute('GET', `/actions/${ACTION}/inspection`)).toBe(true)
    expect(isAllowedRuntimeRoute('POST', `/actions/${ACTION}/inspection/answer`)).toBe(true)
    for (const [method, path] of [
      ['GET', `/tasks/${TASK}/inspection/prepare`],
      ['POST', `/actions/${ACTION}/inspection`],
      ['POST', `/actions/${ACTION}/inspection/answer?url=x`],
      ['POST', '/v1/dispatch'],
      ['POST', `/actions/${ACTION}/attempts`]
    ] as const) {
      expect(isAllowedRuntimeRoute(method, path), path).toBe(false)
    }
  })

  it('passes validated inspection configuration to the runtime, and refuses bad entries', () => {
    expect(validateRuntimeSettings({ publicInspectionHosts: ['GitHub.com', '*.example.org'], inspectionTestOrigins: ['http://127.0.0.1:8811'] })).toEqual({
      LUMI_PUBLIC_INSPECTION_HOSTS: 'github.com,*.example.org',
      LUMI_INSPECTION_TEST_ORIGINS: 'http://127.0.0.1:8811'
    })
    expect(() => validateRuntimeSettings({ publicInspectionHosts: ['localhost'] })).toThrow()
    expect(() => validateRuntimeSettings({ inspectionTestOrigins: ['http://10.0.0.1:80'] })).toThrow()
    expect(validateRuntimeSettings({})).toEqual({})
  })

  it('packaged configuration accepts public hosts only', () => {
    const database = 'postgresql+asyncpg://lumi:x@127.0.0.1:5432/lumi_agent'
    expect(parseRuntimeConfig({ databaseUrl: database, publicInspectionHosts: ['github.com'] })).toMatchObject({
      kind: 'ok', config: { publicInspectionHosts: ['github.com'] }
    })
    expect(parseRuntimeConfig({ databaseUrl: database })).toMatchObject({ kind: 'ok', config: { publicInspectionHosts: [] } })
    for (const hosts of [['localhost'], ['http://127.0.0.1:8811'], 'github.com', [1]]) {
      expect(parseRuntimeConfig({ databaseUrl: database, publicInspectionHosts: hosts }).kind).toBe('invalid')
    }
  })
})

describe('the trusted inspection card', () => {
  const card = parseInspectionAction(examples.action_inspection_waiting)

  it('offers approval only for a pending, unexpired, exact card', () => {
    expect(describeInspection(card, NOW)).toMatchObject({ title: 'Open and read this page?', controls: ['reject', 'approve_and_inspect'] })
    expect(describeInspection(card, Date.parse('2030-01-01T00:00:00Z')).controls).toEqual(['inspect_again'])
  })

  it('never presents an unknown outcome as success or failure, and never retries it', () => {
    const unknown = parseInspection(examples.inspection_outcome_unknown).view
    const model = describeInspection(unknown, NOW)
    expect(model.tone).toBe('uncertain')
    expect(model.controls).toEqual(['inspect_again'])
    expect(model.lines.join(' ')).toContain('A new inspection needs a new approval')
  })

  it('distinguishes "page read" from "question answered"', () => {
    const answered = parseInspection(examples.inspection_answered).view
    expect(describeInspection(answered, NOW)).toMatchObject({ tone: 'success', title: 'Answer from the inspected page' })
    const unanswered = parseInspection(examples.inspection_observed_unanswered).view
    expect(describeInspection(unanswered, NOW)).toMatchObject({ title: 'Page read — no answer yet', controls: ['answer_from_observation', 'inspect_again'] })
    const notVerified: AgentInspectionView = { ...answered, answer: { ...answered.answer!, status: 'not_found', evidence: [] } }
    expect(describeInspection(notVerified, NOW).title).toBe('Could not verify this from the inspected page.')
    const failed = parseInspection(examples.inspection_failed_redirect).view
    expect(describeInspection(failed, NOW).lines[0]).toContain('redirected to an address Lumi may not open')
  })
})
